berries/urls.py
from django.urls import path

from berries.views import BerriesHomeView, SingleProductView, BasketView, ShopView, \
    OrderCheckView, OrderListView, AddToFavoritesView, RemoveFromBasketView, BerryOrderView2

app_name = 'berries'

urlpatterns = [
    path('', BerriesHomeView.as_view(), name='home-page'),
    path('single-product/<int:id>/', SingleProductView.as_view(), name='single-page'),
    path('basket/', BasketView.as_view(), name='basket-page'),
    path('shop/', ShopView.as_view(), name='shop-page'),
    path('add_to_favorites/<int:id>/', AddToFavoritesView.as_view(), name='add_to_favorites'),
    path('remove_from_basket/<int:berry_id>/', RemoveFromBasketView.as_view(), name='remove-from-basket'),
    path('order-check/', OrderCheckView.as_view(), name='order-check'),
    path('berry-order/', BerryOrderView2.as_view(), name='berry-order'),
    path('orders/', OrderListView.as_view(), name='orders'),

]

berries_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django_email_verification import urls as email_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('berries.urls')),
    path('', include('contact.urls')),
    path('', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/urls.py
from django.urls import path

from contact.views import ContactPageView

app_name = 'contact'

urlpatterns = [
    path('contact/', ContactPageView.as_view(), name='contact'),

]

users/urls.py
from django.urls import path
from users.views import RegisterView, ProfileView, LoginView, LogoutView

app_name = 'users'

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile_page')
]

berries/models.py
from django.db import models
from django.contrib.auth import get_user_model

CustomUser = get_user_model()


class Currency(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Categories(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Berries(models.Model):
    name = models.CharField(max_length=50)
    title = models.CharField(max_length=200, null=True, blank=True)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE, default=None)
    description = models.TextField(blank=True, null=True)
    characters = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class BerryImage(models.Model):
    berry = models.ForeignKey(Berries, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='berries_photos')


class Units(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Orders(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField()
    amount = models.DecimalField(max_digits=7, decimal_places=2)
    address = models.CharField(max_length=250)
    phone_number = models.CharField(max_length=13)
    comment = models.TextField(max_length=5000, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Orders2(models.Model):
    category = models.ForeignKey(Categories, on_delete=models.CASCADE)
    berry = models.ForeignKey(Berries, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=7, decimal_places=2)
    address = models.CharField(max_length=250)
    phone_number = models.CharField(max_length=13, blank=True)
    comment = models.TextField(max_length=5000, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.berry)

contact/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=13)
    subject = models.CharField(max_length=50)
    message = models.TextField()


contact/forms.py
from django import forms
from contact.models import Contact


class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = ['name', 'email', 'phone', 'subject', 'message']

contact/views.py
from django.contrib import messages
from django.shortcuts import render
from django.views.generic import TemplateView

from contact.forms import ContactForm


class ContactPageView(TemplateView):
    template_name = 'contact.html'

    def get(self, request, *args, **kwargs):
        form = ContactForm()
        context = {
            'form': form
        }
        return render(request, 'contact.html', context)

    def post(self, request, *args, **kwargs):
        form = ContactForm(request.POST)
        if request.method == 'POST' and form.is_valid():
            form.save()
            messages.success(request, 'Сообщение успешно отправлено!')
            return render(request, 'contact.html')
        context = {
            'form': form
        }
        return render(request, 'contact.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description"
          content="Responsive Bootstrap4 Shop Template, Created by Imran Hossain from https://imransdesign.com/">

    <title>{% block title %} ЕжеМалина {% endblock title %}</title>

    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'Bootsrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/meanmenu.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">


</head>
<body>

<!--PreLoader-->
<div class="loader">
    <div class="loader-inner">
        <div class="circle"></div>
    </div>
</div>
<!--PreLoader Ends-->

<!-- header -->
<div class="top-header-area" id="sticker">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-sm-12 text-center">
                <div class="main-menu-wrap">
                    <!-- logo -->
                    <div class="site-logo">
                        <a href="{% url 'berries:home-page' %}">
                            <img src="{% static 'images/logo.png' %}" alt="">
                        </a>
                    </div>
                    <!-- logo -->

                    <!-- menu start -->
                    <nav class="main-menu">
                        <ul>
                            <li class="current-list-item">
                                <a href="{% url 'berries:home-page' %}">Главная страница</a>
                            </li>
                            <li><a href="#">Страницы</a>
                                <ul class="sub-menu">
                                    <li><a href="{% url 'berries:basket-page' %}">Корзина</a></li>
                                    <li><a href="{% url 'berries:order-check' %}">Проверить</a></li>
                                    <li><a href="{% url 'contact:contact' %}">Контакт с нами</a></li>
                                    <li><a href="{% url 'berries:shop-page' %}">Магазин</a></li>
                                </ul>
                            </li>
                            <li><a href="{% url 'contact:contact' %}">Контакт с нами</a></li>
                            <li><a href="{% url 'berries:shop-page' %}">Магазин</a>
                                <ul class="sub-menu">
                                    <li><a href="{% url 'berries:shop-page' %}">Магазин</a></li>
                                    <li><a href="{% url 'berries:order-check' %}">Проверить</a></li>
                                    <li><a href="{% url 'berries:basket-page' %}">Корзина</a></li>
                                    <li><a href="{% url 'berries:berry-order' %}">Заказать</a></li>
                                </ul>
                            </li>
                            {% if request.user.is_authenticated %}
                                <li><a href="{% url 'users:profile_page' %}">Профиль</a>
                                    <ul class="sub-menu">
                                        <li><a href="{% url 'users:profile_page' %}">Профиль</a></li>
                                        <li><a href="{% url 'users:logout' %}">Выйти</a></li>
                                    </ul>
                                </li>
                            {% else %}
                                <li><a href="#">Войти</a>
                                    <ul class="sub-menu">
                                        <li><a href="{% url 'users:login' %}">Логин</a></li>
                                        <li><a href="{% url 'users:register' %}">Регистация</a></li>
                                    </ul>
                                </li>
                            {% endif %}
                            <li>
                                <div class="header-icons">
                                    <a class="shopping-cart" href="{% url 'berries:basket-page' %}"><i
                                            class="fas fa-shopping-cart"></i></a>
                                    <a class="mobile-hide search-bar-icon" href="#"><i class="fas fa-search"></i></a>
                                </div>
                            </li>
                        </ul>
                    </nav>
                    <a class="mobile-show search-bar-icon" href="#"><i class="fas fa-search"></i></a>
                    <div class="mobile-menu"></div>
                    <!-- menu end -->
                </div>
            </div>
        </div>
    </div>
</div>


{% block content %}

{% endblock content %}

    {% block logo_carousel %}
<!-- logo carousel -->
<div class="logo-carousel-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="logo-carousel-inner">
                    {% for berry in berries %}
                        {% for berry_image in berry.berryimage_set.all|slice:"1" %}
                            <div class="single-logo-item">
                                <img src="{{ berry_image.image.url }}" alt="">
                            </div>
                        {% endfor %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock logo_carousel %}

<!-- end logo carousel -->

<!-- footer -->
<div class="footer-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6">
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="footer-box get-in-touch">
                    <h2 class="widget-title">Связаться</h2>
                    <ul>
                        <li>34/8, Tashkent region, Chirchik, A.Temur 95-3</li>
                        <li>sanjarwer92@gmail.com</li>
                        <li>s.maxmudov@uztex.uz</li>
                        <li>+998 94 924 63 03</li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="footer-box pages">
                    <h2 class="widget-title">Страницы</h2>
                    <ul>
                        <li><a href="{% url 'berries:home-page' %}">Главная страница</a></li>
                        <li><a href="{% url 'berries:order-check' %}">Проверит</a></li>
                        <li><a href="{% url 'berries:shop-page' %}">Магазин</a></li>
                        <li><a href="{% url 'berries:basket-page' %}">Корзина</a></li>
                        <li><a href="{% url 'contact:contact' %}">Связ с нами</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="footer-box subscribe">
                    <h2 class="widget-title">Подписаться</h2>
                    <p>Подпишитесь на нашу рассылку, чтобы получать последние обновления.</p>
                    <form action="index.html">
                        <input type="email" placeholder="Email">
                        <button type="submit"><i class="fas fa-paper-plane"></i></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end footer -->

<!-- copyright -->
<div class="copyright">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-12">
                <p>Copyrights &copy; 2019 - <a href="https://imransdesign.com/">Imran Hossain</a>, All Rights Reserved.
                </p>
            </div>
            <div class="col-lg-6 text-right col-md-12">
                <div class="social-icons">
                    <ul>
                        <li><a href="https://www.facebook.com/sanjar.utkirovich?mibextid=ZbWKwL" target="_blank"><i
                                class="fab fa-facebook-f"></i></a></li>
                        <li><a href="https://t.me/cocksure" target="_blank"><i class="fab fa-telegram"></i></a></li>
                        <li>
                            <a href="https://www.instagram.com/__maxmudov/?fbclid=IwAR1j34PBpgmZa_ILZe4x4HN6QAI4V1A8puBlIlBeM-Vn23fjLdzUaa776_Q"
                               target="_blank"><i class="fab fa-instagram"></i></a></li>
                        <li><a href="https://github.com/cocksure" target="_blank"><i class="fab fa-github"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end copyright -->

<script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
<script src="{% static 'Bootsrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.countdown.js' %}"></script>
<script src="{% static 'js/jquery.isotope-3.0.6.min.js' %}"></script>
<script src="{% static 'js/waypoints.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/jquery.meanmenu.min.js' %}"></script>
<script src="{% static 'js/sticker.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>


</body>
</html>

templates/basket.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Корзина {% endblock title %}

{% block content %}

    <!-- breadcrumb-section -->
    <div class="breadcrumb-section breadcrumb-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2 text-center">
                    <div class="breadcrumb-text">
                        <p>Свежий и органический</p>
                        <h1>Корзина</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end breadcrumb section -->

    <!-- cart -->

    <div class="cart-section mt-150 mb-150">
        <div class="container">

            {% if messages %}
                {% for message in messages %}
                    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}

                <script>
                    setTimeout(function () {
                        var alerts = document.querySelectorAll('.alert');
                        for (var i = 0; i < alerts.length; i++) {
                            alerts[i].style.display = 'none';
                        }
                    }, 5000); // Скрыть сообщения через 5 секунд
                </script>
            {% endif %}

            <div class="row">
                <div class="col-lg-8 col-md-12">
                    <div class="cart-table-wrap">
                        <table class="cart-table">
                            <thead class="cart-table-head">
                            <tr class="table-head-row">
                                <th class="product-remove"></th>
                                <th class="product-image">Изображение продукта</th>
                                <th class="product-name">Название</th>
                                <th class="product-price">Цена</th>
                                <th class="product-quantity">Количество</th>
                                <th class="product-total">Общий</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for berry in berries %}
                                <tr class="table-body-row">
                                    <td class="product-remove">
                                        <a href="{% url 'berries:remove-from-basket' berry.id %}">
                                            <i class="far fa-window-close"></i>
                                        </a>
                                    </td>

                                    {% with berry_image=berry.berryimage_set.first %}
                                        {% if berry_image %}
                                            <td class="product-image"><img src="{{ berry_image.image.url }}" alt="">
                                            </td>
                                        {% else %}
                                            <td class="product-image"><img
                                                    src="{% static 'path/to/placeholder/image.jpg' %}" alt="No Image">
                                            </td>
                                        {% endif %}
                                    {% endwith %}

                                    <td class="product-name">{{ berry.name }}</td>
                                    <td class="product-price">{{ berry.price }}</td>
                                    <td class="product-quantity">
                                        <input type="number" name="quantity" class="quantity-input" value="1" min="1">
                                    </td>
                                    <td class="product-total">
                                        $<span class="item-total">{{ berry.price }}</span>
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="6">Ваша корзина пуста.</td>
                                </tr>
                            {% endfor %}
                            </tbody>

                        </table>
                    </div>
                </div>


                <div class="col-lg-4">
                    <div class="total-section">
                        <table class="total-table">
                            <thead class="total-table-head">
                            <tr class="table-total-row">
                                <th>Общий</th>
                                <th>Цена</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr class="total-data">
                                <td><strong>Итого: </strong></td>
                                <td id="subtotal"></td>
                            </tr>
                            <tr class="total-data">
                                <td><strong>Доставка: </strong></td>
                                <td>$10</td>
                            </tr>
                            <tr class="total-data">
                                <td><strong>Всего/Итого:</strong></td>
                                <td id="total"></td>
                            </tr>
                            </tbody>
                        </table>
                        <div class="cart-buttons">
                            <a href="{% url 'berries:basket-page' %}" class="boxed-btn">Обновить корзину</a>
                            <a href="{% url 'berries:order-check' %}" class="boxed-btn black">Проверить</a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- end cart -->

    <!-- Подключение JavaScript-файла -->
    <script src="{% static 'css/main.css' %}"></script>

{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Главная страница {% endblock title %}

<!-- end header -->
{% block content %}

    <!-- hero area -->
    <div class="hero-area hero-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-9 offset-lg-2 text-center">
                    <div class="hero-text">
                        <div class="hero-text-tablecell">
                            <p class="subtitle">Свежий & Органический</p>
                            <h1>Вкусные сезонные фрукты</h1>
                            <div class="hero-btns">
                                <a href="{% url 'berries:shop-page' %}" class="boxed-btn">Ягодная коллекция</a>
                                <a href="{% url 'contact:contact' %}" class="bordered-btn">Связ с нами</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end hero area -->

    <!-- features list section -->
    <div class="list-section pt-80 pb-80">
        <div class="container">

            <div class="row">
                <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
                    <div class="list-box d-flex align-items-center">
                        <div class="list-icon">
                            <i class="fas fa-shipping-fast"></i>
                        </div>
                        <div class="content">
                            <h3>Бесплатная доставка</h3>
                            <p>При заказе на сумму более 75$</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
                    <div class="list-box d-flex align-items-center">
                        <div class="list-icon">
                            <i class="fas fa-phone-volume"></i>
                        </div>
                        <div class="content">
                            <h3>24/7 поддержка</h3>
                            <p>Получите поддержку в течение всего дня</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="list-box d-flex justify-content-start align-items-center">
                        <div class="list-icon">
                            <i class="fas fa-sync"></i>
                        </div>
                        <div class="content">
                            <h3>Возвращать деньги</h3>
                            <p>Получите возврат в течение 3 дней!</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- end features list section -->

    <!-- product section -->
    <div class="product-section mt-150 mb-150">
        <div class="container">

            <div class="row">
                <div class="col-md-12">
                    <div class="product-filters">
                        <ul>
                            <li class="{% if not request.GET.category %}active{% endif %}">
                                <a href="{% url 'berries:shop-page' %}">Все</a>
                            </li>
                            {% for category in categories %}
                                <li class="{% if request.GET.category == category.pk %}active{% endif %}">
                                    <a href="?category={{ category.pk }}">{{ category.name }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>

            <div class="row product-lists">

                {% for berry in berries %}
                    <div class="col-lg-4 col-md-6 text-center {{ berry.category.name|slugify }}">
                        <div class="single-product-item">
                            <div class="product-image">
                                {% for berry_image in berry.berryimage_set.all|slice:"1" %}
                                    <a href="{% url 'berries:single-page' berry.id %}">
                                        <img src="{{ berry_image.image.url }}" alt="">
                                    </a>
                                {% endfor %}
                            </div>
                            <h3>{{ berry }}</h3>
                            <p class="product-price"><span>Per Kg</span>{{ berry.price }}</p>
                            <form action="{% url 'berries:add_to_favorites' berry.id %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="cart-btn">
                                    <i class="fas fa-shopping-cart"></i>Добавить в корзину
                                </button>
                            </form>
                        </div>
                    </div>
                {% endfor %}

            </div>
            <hr>
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="pagination-wrap">
                        <ul>
                            <li><a href="{{ page_obj.previous_page_number }}">Prev</a></li>
                            {% for num in page_obj.paginator.page_range %}
                                <li{% if page_obj.number == num %} class="active"{% endif %}>
                                    <a href="?page=
                                            {{ num }}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}">
                                        {{ num }}
                                    </a>
                                </li>
                            {% endfor %}
                            <li><a href="{{ page_obj.next_page_number }}">Next</a></li>
                        </ul>
                    </div>
                </div>
            </div>


        </div>
    </div>
    <!-- end product section -->



{% endblock content %}
	

templates/single-product.html
{% extends 'base.html' %}
{% load static %}


{% block title %} Информация ягод {% endblock title %}


{% block content %}
    <!-- breadcrumb-section -->
    <div class="breadcrumb-section breadcrumb-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2 text-center">
                    <div class="breadcrumb-text">
                        <p>Подробнее</p>
                        <h1>Информация о товаре</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end breadcrumb section -->

    <!-- single product -->
    <div class="single-product mt-150 mb-150">
        <div class="container">
            <div class="row">
                <div class="col-md-5">

                    {% for berry_image in berries.berryimage_set.all %}
                        {% if berry_image == berries.berryimage_set.all.first %}

                            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">

                            <div class="carousel-item active">
                                <img src="{{ berry_image.image.url }}" class="d-block w-100" alt="...">
                            </div>
                        {% else %}
                            <div class="carousel-item">
                                <img src="{{ berry_image.image.url }}" class="d-block w-100" alt="...">
                            </div>
                        {% endif %}
                    {% endfor %}
                    </div>
                    <button class="carousel-control-prev" style="opacity: 0%" type="button"
                            data-target="#carouselExampleControls" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </button>

                    <button class="carousel-control-next" style="opacity: 0%" type="button"
                            data-target="#carouselExampleControls" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </button>
                    </div>


                </div>
                <div class="col-md-7">
                    <div class="single-product-content">
                        <h3>{{ berries.name }}</h3>
                        <h4>{{ berries.title }}</h4>
                        <p class="single-product-pricing"><span>Per Kg</span> {{ berries.currency }}{{ berries.price }}
                        </p>
                        <p><strong>Описание:</strong> {{ berries.description }}</p>
                        <hr>
                        <p><strong>Характеристики</strong></p>
                        {% for characteristic in berries.characters.splitlines %}
                            <p>{{ characteristic }}</p>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </div>
    {% block logo_carousel %}{% endblock %}

{% endblock content %}